### ISSUE TITLE
Fazetové vyhľadávanie nad datasetmi

### ISSUE THREAD

**Issue by miroslavliska** [slovak-egov/nkod-portal#1]
Hlavné fazetové vyhľadávanie musí mať nasledovné vlastnosti:
Je možné vyhľadávať podľa
- Typ datasetu
- Téma datasetu
- Poskytovateľ
- Formát
- Klúčové slovo
- Periodicita aktualizácie

Pri výbere z hodnôt jednotlivých položiek je potrebné poskytnúť podporný textový vyhľadávací prvok, ktorý filtruje hodnoty v zoznamoch.

**Comment by lk8w** [comment]
Tu by sa hodilo ešte filtrovanie podľa periodicity aktualizácie

**Comment by miroslavliska** [comment]
> Tu by sa hodilo ešte filtrovanie podľa periodicity aktualizácie

OK, pridávam.

**Comment by hornik-informo** [comment]
Táto požiadavka bola zapracovaná do vývojovej verzie.
