### ISSUE TITLE
Prehľadnosť zoznamu datasetov

### ISSUE THREAD

**Issue by lk8w** [slovak-egov/nkod-portal#10]
Názov poskytovateľa datasetu viditeľnejšie oddeliť od popisu datasetu (napr. podfarbením, inou farbou písma, inou proporciou písma, rámčekom, ...)
![obrázok](https://github.com/slovak-egov/nkod-portal/assets/149062360/1d95b9e2-295c-446c-8af3-464d3115343b)
![obrázok](https://github.com/slovak-egov/nkod-portal/assets/149062360/f9529ef0-08bd-46de-91cd-a8c886771a2a)

**Comment by hornik-informo** [comment]
Vo vývojovej verzii je táto požiadavka zapracovaná.
