### ISSUE TITLE
Vytvorenie/aktualizácia architektúry riešenia OD2.0-Komunita

### ISSUE THREAD

**Issue by miroslavliska** [slovak-egov/nkod-portal#100]
Vytvorenie architektúry riešenia OD2.0-Komunita - aktualizácia modelu projektu opendata v EA.

**Comment by elazenga** [comment]
![Navrh_SSO_20240225](https://github.com/slovak-egov/nkod-portal/assets/93482922/740fbe59-b290-46fd-a81c-bd1665938eef)
