### ISSUE TITLE
Vytvorenie/aktualizácia návrhu obrazoviek OD2.0-Komunita

### ISSUE THREAD

**Issue by miroslavliska** [slovak-egov/nkod-portal#101]
Vytvorenie/aktualizácia návrhu obrazoviek OD2.0-Komunita
+ sprístupnenie modelu na pripomienkovanie

**Comment by elazenga** [comment]
https://www.figma.com/proto/XoG3Ol5VC9WAQ3bnYEDaD1/2024-02-19-OpenData2.0-GUI-SSO?type=design&node-id=16-7131&t=EYvsA76CGN71wEmF-0&scaling=contain&page-id=0%3A1
