### ISSUE TITLE
Serializácia vlastnosti - je publikovaný?

### ISSUE THREAD

**Issue by miroslavliska** [slovak-egov/nkod-portal#102]
Namiesto tripletu:

`X   <https://data.gov.sk/custom/shouldBePublic> "True" .
`

prosím používať tento

`X  <https://data.gov.sk/def/ontology/egov/isPublic> "true"^^<http://www.w3.org/2001/XMLSchema#boolean> .
`

**Comment by hornik-informo** [comment]
Táto vlastnosť je len pre portál a znamená, či by dataset mal byť publikovaný, to neznamená, že je publikovaný. Dataset bez distribúcií je nepublikovaný aj keď zverejňovateľ publikáciu povolil.

**Comment by miroslavliska** [comment]
OK, rozumiem, tento level nebudem riesit ani prenasat do databazy.
