### ISSUE TITLE
Nesprávny poskytovateľ LKODu Znalostného grafu 

### ISSUE THREAD

**Issue by miroslavliska** [slovak-egov/nkod-portal#103]
V súbore pre LKOD so Znalostným grafom SR v súbore 2915d43bb06c4e6eb3c2446f01668bfc.ttl
je nesprávny (navyše) vydavateľ datasetu štatistický úrad. Vyzerá to, akoby oba LKODy mali rovnaké URI. Kto vie kde to vzniklo.
![image](https://github.com/slovak-egov/nkod-portal/assets/37801000/3cb7c28c-478a-438f-9ffa-8c8d76786621)

**Comment by hornik-informo** [comment]
Vzniklo to tu:
https://github.com/datova-kancelaria/nkod-registrace/blob/main/lkody/lkod-datacube-su.ttl

**Comment by miroslavliska** [comment]
Aha, tak to bola si moja chyba, na develop branchi je to vsetko novsie. Prosim o opravu v NKODe. Ińak ak sa mozem spyat, uz asi nepotrebujeme vobec https://github.com/datova-kancelaria/nkod-registrace, ze? I tak bol planovy ako docasny repozitar. Ze by som ho mohol v githube archivovat,

**Comment by hornik-informo** [comment]
Ten repozitár už nie je potrebný a obsah registračného súboru sme upravili.

**Comment by miroslavliska** [comment]
> Ten repozitár už nie je potrebný a obsah registračného súboru sme upravili.

OK ďakujem za info, repozitár som archivoval. Task zatváram.
