### ISSUE TITLE
Nesprávne URL distribúcie na stiahnutie

### ISSUE THREAD

**Issue by miroslavliska** [slovak-egov/nkod-portal#105]
Napr. dataset https://data.slovensko.sk/datasety/eec7bfcd76421af279ad50e1e06d5911
má jednu distribúciu na stiahnutie, ktorá sa dá cez portál stiahnuť cez link: https://data.slovensko.sk/download?id=14489366-ef0f-4260-871e-99ed13f88e17

Avšak keď sa pozriem cez SPARQL endpoint, tak vidím iný (nesprávny link na stiahnutie)
![image](https://github.com/slovak-egov/nkod-portal/assets/37801000/99d724ef-6ef8-42da-bd62-88486807249b)

Som toho názoru, že by mali byť oba linky funkčné, a rovnaké. Ak získam URL odkazy cez SPARQL enpoint, tak si tento konkrétne nebudem vedieť stiahnuť.

**Comment by hornik-informo** [comment]
Zostalo to po manuálnych zásahoch chybných dát z data.gov.sk, zaktualizovali sme to, aby aj v súborocvh datasetov boli správne linky.

**Comment by miroslavliska** [comment]
OK, zatváram tento task.
