### ISSUE TITLE
Zobrazovanie URI, dátumu vytvorenia a dátumu modifikácie na datasete

### ISSUE THREAD

**Issue by miroslavliska** [slovak-egov/nkod-portal#106]
V detaile datasetu chýbajú nasledovné údaje: 

- [ ] URI datasetu
- [ ] Dátum vytvorenia
- [ ] Dátum zobrazenia

Prosím o ich pridanie.

**Comment by miroslavliska** [comment]
TOP priorita pre WPNKOD-SLA

**Comment by hornik-informo** [comment]
Zmena bola nasadená.
