### ISSUE TITLE
Nejde sťahovať nové distribúcie nahraté na data.slovensko.sk (chyba nginx - prepisovanie https na http)

### ISSUE THREAD

**Issue by miroslavliska** [slovak-egov/nkod-portal#109]
Napr. dataset NASESu
https://data.slovensko.sk/datasety/bfdfea87-dec4-4e2d-8c10-6f9ac0c3b773

má dve distribúcie XSLX. Ani mne, ani kolegom z NASESu sa nedajú tieto distribúcie stiahnuť, aj keď sú okamžite nahrané.

Podobne dataset Ministerstva hospodárstva
https://data.slovensko.sk/datasety/ed59c28b-230e-4127-bcb7-92e56f1cd4cf

má districiu Excelu, aj ODS. Ani jedna sa mi nedá stiahnuť. Prosím o preverenie.

**Comment by hornik-informo** [comment]
Môžete definovať to, že sa nedajú stiahnuť, lebo to mlže byť nejaké obmedzenie, ktoré my nemáme.

![image](https://github.com/slovak-egov/nkod-portal/assets/144911183/cc221e9c-f1e2-413c-bf74-e866308a0821)

**Comment by miroslavliska** [comment]
OK, myslím že sme sa v identifikácii problému posunuli. Aj excelové distribúcie tohto datasetu
https://data.slovensko.sk/datasety/bfdfea87-dec4-4e2d-8c10-6f9ac0c3b773

sa dajú stiahnuť, ak použijete iný prehliadač ako chrome. Vo firefoxe nám to viacerým ide, v chrome nie. 

Avšak iné excelové distribúcie stiahnuť ide. Po komunikácii s poskytovateľom sme prišli na to, že tento problém vzniká len pri tých distribúciach, ktoré boli zmenené. Tam pravdepodobne chrom zabráni stiahnutiu, asi kvoli nejakému bezpečnostnému opatreniu.

**Comment by hornik-informo** [comment]
Problém je odstránený. Pri prechode cez nginx (komponenta NKOD) dochádzalo k prepisu adries vložených súborov z https na http a to bolo v Chrome zablokované.

**Comment by miroslavliska** [comment]
Je to v poriadku, zatváram task.

**Comment by hornik-informo** [comment]
Budeme musieť vstúpiť do všetkých distribúcií, pretože toto je adresa archiv.statistics.sk a ako http:// bola importovaná z data.gov.sk. Zároveň budeme musieť vyžadovať zabezpečené adresy pre distrubúcie mimo data.slovensko.sk pri vkladaní distribúcie cez formulár.

**Comment by hornik-informo** [comment]
Urobili sme prepis všetkých adries distribúcií z http na https.

**Comment by miroslavliska** [comment]
OK, otestoval som nahlásený dataset, je to v poriadku. Task zatváram.
