### ISSUE TITLE
Zoraďovanie datasetov podľa času modifikácie

### ISSUE THREAD

**Issue by lk8w** [slovak-egov/nkod-portal#11]
Umožniť zoradenie datasetov podľa dátumu poslednej modifikácie (súčasný portál toto umožňuje)

**Comment by miroslavliska** [comment]
Len najskôr musíme rozšíriť DCAT-AP-SK2.0 na novú verziu, kde sa bude ukladať/harvestovať aj údaj dct:issued.
Takže táto požiadavka sa nedá zaradiť do NKOD-23.12 ale do ďaľších verzíí.

https://github.com/datova-kancelaria/dcat-ap-sk-2.0/issues/2

**Comment by lk8w** [comment]
A urobiť to cez dct:temporal? Zoradenie podľa časového pokrytia? To by išlo?

**Comment by miroslavliska** [comment]
> A urobiť to cez dct:temporal? Zoradenie podľa časového pokrytia? To by išlo?

Toto asi nie je dobrá cesta. Jednak väčšina datasetov toto nemá ani nastavené - pretože to sa v dátach neevidovalo. Tento údaj sa bude postupne plniť, ale i tak to nebude vhodný údaj na sortovanie - tým že je to vlastne interval. Nevymýšlal by som tu radšej potemkina, ale zameral by som sa na ten DCAT-AP-SK2.1, kde bude dct:issued

**Comment by hornik-informo** [comment]
Prosím uzatvoriť, ak nie je relevantné pre M4.

**Comment by miroslavliska** [comment]
Tento task uzatváram ako implementovaný. Ak je zoznam zobrazený bez vyhľadávania, tak je zoradený podľa dátumi modifikácie. Ak sa jedná o vyhľadávanie, tak je zoznam zoradený podľa skóre.

**Comment by lk8w** [comment]
Toto mi nejako nesedí, lebo keď dám zoradiť datasety podľa modifikácie vidím:
![obrázok](https://github.com/slovak-egov/nkod-portal/assets/149062360/92f96fb8-bb9d-449e-8d0e-ad0d6ed60903)
Na portáli vidím:
![obrázok](https://github.com/slovak-egov/nkod-portal/assets/149062360/615a1880-d60f-4fb9-82ea-3623f217d324)

**Comment by hornik-informo** [comment]
Harvestuje sa raz denne, preto má portál vždy aktuálnejšie dáta.

**Comment by lk8w** [comment]
Áno a teraz som si všimol ze SPARQL vypisuje aj datasety, ktoré majú modifikáciu dátum, ktorý ešte nebol. To by mala byť chyba, dataset nemôže mať dátum modifikácie v budúcnosti. Takýchto datasetov je 71.
![obrázok](https://github.com/slovak-egov/nkod-portal/assets/149062360/a90ac6e9-2204-4b94-9b10-d71c75954664)
