### ISSUE TITLE
Nesprávny poskytovateľ datasetov (Úrad pre reguláciu hazardných hier)?

### ISSUE THREAD

**Issue by miroslavliska** [slovak-egov/nkod-portal#112]
Dobrý deň, 

práve sme dostali toto nahlásené cez platformu slovensko digital
https://platforma.slovensko.digital/t/dennik-np-opendata-2-0/7933/190?u=liska

![image](https://github.com/slovak-egov/nkod-portal/assets/37801000/aea7dcc4-e662-4d97-909e-8148c9c999e1)

Rozmýšlam, ako sa tam takýto poskytovateľ objavil.

**Comment by hornik-informo** [comment]
Bol aj na data.gov.sk. Je s ním niečo v neporiadku?

**Comment by hornik-informo** [comment]
Dataset logicky patrí pod mesto Tvrdošín a priradenie vzniklo duplicitou IČO v preklade starých URI na nové.

https://data.gov.sk/id/legal-subject/3999144d-df5a-41bc-9eeb-1ac775e7bb61,Úrad pre reguláciu hazardných hier,52265021
https://data.gov.sk/id/legal-subject/c6a412fc-400d-4b35-ba4f-257262176d0e,Mesto Tvrdošín (OVM),52265021

**Comment by miroslavliska** [comment]
> Dataset logicky patrí pod mesto Tvrdošín a priradenie vzniklo duplicitou IČO v preklade starých URI na nové.
> 
> [https://data.gov.sk/id/legal-subject/3999144d-df5a-41bc-9eeb-1ac775e7bb61,Úrad](https://data.gov.sk/id/legal-subject/3999144d-df5a-41bc-9eeb-1ac775e7bb61,%C3%9Arad) pre reguláciu hazardných hier,52265021 https://data.gov.sk/id/legal-subject/c6a412fc-400d-4b35-ba4f-257262176d0e,Mesto Tvrdošín (OVM),52265021

Aha, rozumiem, ďakujem za vysvetlenie. Ospravedlňujem sa, že som to hneď assignol na Vás, asi by som túto chybu odhalil aj sám. Aby ste sa radšej venovali dôležitejším veciam než táto, zajtra identifikujem všetky datasety zo starého portálu, ktoré patrili pod úrad na reguláciu a postnem ho sem, aby sa to potom mohlo na novom opraviť.
