### ISSUE TITLE
Príprava číselníkov pre komunitu

### ISSUE THREAD

**Issue by miroslavliska** [slovak-egov/nkod-portal#117]
Podnety
- [x] stavy podnetu {nový, riešený ....}
- [x] typ podnetu {zverejnenie nového datasetu, nekvalita datasetu, }

**Comment by lk8w** [comment]
Typ podnetu:
1. podnet na zverejnenie nového datasetu/API
2. podnet na kvalitu zverejneného datasetu/API
3. podnet na chýbajúce metadáta zverejneného datasetu/API
4. podnet na nefunkčnosť odkazu na stiahnutie datasetu/API

**Comment by lk8w** [comment]
Stav podnetu:

1. zaevidovaný (po vytvorení podnetu)
2. v riešení (po tom čo sa ujasní, kto bude podnet riešiť a daný poskytovateľ/OVM s tým súhlasí)
3. vyriešený (po oprave metadát, po oprave datasetu, po zverejnení datasetu)
