### ISSUE TITLE
Zobrazenie datasetu

### ISSUE THREAD

**Issue by lk8w** [slovak-egov/nkod-portal#12]
Pridať do zobrazenia metadát datasetu kontakt na správcu datasetu, dátum vytvorenia datasetu, dátum poslednej úpravy, licenciu.

**Comment by miroslavliska** [comment]
Toto je duplicitná požiadavka s https://github.com/slovak-egov/nkod-portal/issues/4 
Ak ešte niečo chýba, treba to uviesť tam.
Takže požiadavku zatváram.
