### ISSUE TITLE
Nesprávny čas vytvorenie datasetu - v budúcnosti

### ISSUE THREAD

**Issue by miroslavliska** [slovak-egov/nkod-portal#121]
Napr. dôležitý dataset, ktorý sa používa inými ISVS
https://data.slovensko.sk/datasety/55de1b2f-d1bc-4f0b-9b09-b9bd9a439670

má dátum vytvorenia v budúcnosti:
![image](https://github.com/slovak-egov/nkod-portal/assets/37801000/3c29ec2c-aa7f-412d-9f43-dea1f8581f59)

**Comment by hornik-informo** [comment]
Dátum je tam 28.3.2018, mám vidieť niečo iné?

**Comment by miroslavliska** [comment]
ach, jaj, nevšimol som si rok 2018. moja chyba.
