### ISSUE TITLE
Neprístupnosť odkazov "Technická Podpora" a "Podnety na zverejnenie údajov"

### ISSUE THREAD

**Issue by nervous-inhuman** [slovak-egov/nkod-portal#129]
Zdravím, 

ak sa pokusím otvoriť linky "Technická Podpora" a "Podnety na zverejnenie údajov" ktoré sú vo footeri NKOD Portálu, po presmerovaní na odkaz, ktorý je hostovaný na https://wiki.vicepremier.gov.sk dostanem 403 Forbidden chybu.

Je vyššie spomínaná wiki geoblokovaná mimo Slovenska? (Na internet pristupujem z Nemeckej IP adresy)

**Comment by miroslavliska** [comment]
> Zdravím,
> 
> ak sa pokusím otvoriť linky "Technická Podpora" a "Podnety na zverejnenie údajov" ktoré sú vo footeri NKOD Portálu, po presmerovaní na odkaz, ktorý je hostovaný na https://wiki.vicepremier.gov.sk dostanem 403 Forbidden chybu.
> 
> Je vyššie spomínaná wiki geoblokovaná mimo Slovenska? (Na internet pristupujem z Nemeckej IP adresy)

Dobrý deň. Áno, priestor technickej podpory pre data.slovensko.sk beží v Confluence MetaIS, ktorý bol z dôvodu útokov nastavený iba pre prístup z SK. S príchodom nového MetaIS je plán opustiť toto confluence a prejsť na iné riešenie. V súčasnosti ešte neviem presne povedať kedy sa tak stane.
