### ISSUE TITLE
Naharvestované datasety Levoče sa nezobrazujú v portáli

### ISSUE THREAD

**Issue by miroslavliska** [slovak-egov/nkod-portal#130]
Keď som kontrolovať LKOD Mesta Levoča, všimol som si, že cez harvester prejdú, aj sa naloadujú do DB, viď:
![image](https://github.com/slovak-egov/nkod-portal/assets/37801000/4424ad33-7832-4cf0-8b2b-f0e81460e02a)

avšak dataset sa nedá nájsť aj v portáli data.slovensko.sk
https://data.gov.sk/set/ee5bbd7c27d678518e2ffb5ba22bb10a

Prosím o kontrolu, prečo sa nezobrazuje.

**Comment by hornik-informo** [comment]
Spomínal som to už, že sme nemohli spustiť preberanie naharvestovaného obsahu v čase, keď bolo naharvestované málo alebo nič, pretože by sa akurát všetky datasety katalógov zmazali a neprenieslo by sa dohromady nič. 
Môžeme to spustiť teraz? 
Naharvestované katalógy budú aktualizované a tie, ktoré nemajú žiadny dataset v grafovej databáze nebudú mať žiadny ani na portáli.

Od toho spustenia budú každý deň katalógy aktualizované podľa stavu v grafovej databáze.

**Comment by miroslavliska** [comment]
> Spomínal som to už, že sme nemohli spustiť preberanie naharvestovaného obsahu v čase, keď bolo naharvestované málo alebo nič, pretože by sa akurát všetky datasety katalógov zmazali a neprenieslo by sa dohromady nič. Môžeme to spustiť teraz? Naharvestované katalógy budú aktualizované a tie, ktoré nemajú žiadny dataset v grafovej databáze nebudú mať žiadny ani na portáli.
> 
> Od toho spustenia budú každý deň katalógy aktualizované podľa stavu v grafovej databáze.

Dobrý deň, áno prosím, aby to bolo nastavené podľa reálneho harvestovania. Včera som našiel množstvo chýb, ktoré som reportoval ich poskytovateľom. Pokiaľ viem, aspoň 3 katalógy by sa mali harvestovať v poriadku, a to Zvolen, Levoča a čiastočne aj MFSR.

**Comment by hornik-informo** [comment]
Portál je spárovaný s harvesterom a naharvestovaný obsah je zahrnutý do portálu. Aktuálne je to MFSR, Zvolen, Levoča.

V rámci LKODu MFSR je aj dataset iného poskytovateľa https://opendata.mfsr.sk/opendata/catalog/organizacna-struktura-urhh a tomuto by sa zrejme malo zabrániť, inak si poskytovatelia budú zasahovať do svojho obsahu.
