### ISSUE TITLE
Nie je možné dotazovať vybrané vlastnosti datasetov cez SPARQL Endpoint

### ISSUE THREAD

**Issue by miroslavliska** [slovak-egov/nkod-portal#131]
1) Najvyššia dátová séria - [Zoznam schránok na doručovanie](https://data.gov.sk/set/55de1b2f-d1bc-4f0b-9b09-b9bd9a439670) - mi vráti podradené datasety, napr. 
![image](https://github.com/slovak-egov/nkod-portal/assets/37801000/8e98b9af-ca08-4142-8959-b3342f34969f)

2) Tieto podradené datasety sú dátové série, a ja chcem získať ešte ich podradené datasety, ktoré sú už klasické dátové datasety. Keď sa ale spýtam rovnaký dotaz ako v bode 1, pre podradenú dátovú sériu:
![image](https://github.com/slovak-egov/nkod-portal/assets/37801000/81e1d5b6-eb19-4db8-a496-41dc6d19adfe)

tak výsledné vlastnosti tejto podradenej dátovej série [Zoznam schránok na doručovanie FO](https://data.gov.sk/set/dce81519-73df-4f5f-9ef6-149c11cb607d), vôbec neobsahujú informácie o podradených datasetoch, tj. dct:hasPart a neviem sa k nim dotazom dostať, čo je podľa mňa bug, pretože na GUI vidím správny podradený dataset. 

Chýba tu triplet na podradený dataset.

3) 

Keď si podradený dataset pozriem cez GUI, tj. 
[Zoznam elektronických schránok FO aktivovaných na doručenie (2024-03-31)
](https://data.slovensko.sk/datasety/e84b6cbe-8a74-43fb-88aa-dbb7954c1bef)

tak ho síce cez GUI vidím, ale vôbec ho nevidím cez SPARQL Endpoint. 
![image](https://github.com/slovak-egov/nkod-portal/assets/37801000/875cf926-527c-48c9-a7a7-4e8cd7953861)

Toto je veľmi dôležité opraviť, nedá sa dopytovať!

4) 

Táto úloha súvisí aj s pripravou zmenou na prechod na DCAT-AP-SK-3.0.0
https://github.com/slovak-egov/centralny-model-udajov/issues/16

kde napr. presne v tomto dotknutom prípade, má byť vlastnosť - nadradený dataset - serializovaná ako [dcat:inSeries](https://www.w3.org/TR/vocab-dcat-3/#Property:dataset_in_series), a dátová séria už má vlastnú triedu, [dcat:DatasetSeries](https://semiceu.github.io/DCAT-AP/releases/3.0.0/#DatasetSeries). Neviem či je možné opraviť túto chybu rovno so zmenou prvých týchto dvoch vecí pre DCAT-AP-SK-3.0.0. Ak nie, tak prosím o opravu aj bez toho, pretože sa nedá dotazovať.

**Comment by hornik-informo** [comment]
dct:hasPart je súčasťou DCAT-AP-SK?

**Comment by hornik-informo** [comment]
Dataset https://data.slovensko.sk/datasety/e84b6cbe-8a74-43fb-88aa-dbb7954c1bef nie je publikovaný a preto nie je v public adresároch a preto sa nenaharvestoval do grafovej databázy. Samozrejme po publikácii je potrebné počkať na ďalšiu harvestáciu.

**Comment by miroslavliska** [comment]
> Dataset https://data.slovensko.sk/datasety/e84b6cbe-8a74-43fb-88aa-dbb7954c1bef nie je publikovaný a preto nie je v public adresároch a preto sa nenaharvestoval do grafovej databázy. Samozrejme po publikácii je potrebné počkať na ďalšiu harvestáciu.

Aha, beriem to, bol som prihlásený ako superadmin, takže preto som ho videl. Musím si na to dávať pozor, keď robím dokumentáciu. 

> dct:hasPart je súčasťou DCAT-AP-SK?

V tom prvom dotaze, celkom hore to vidím, ale rozmýšlam, či to náhodou tam nevkladá harvester (je to inverzná relácia k dct:isPartOf). Asi je to tak. Takže zatiaľ tento task zatváram, bez chyby. (Najlepší scenár).
