### ISSUE TITLE
Je možné zmazať komentár niekoho iného

### ISSUE THREAD

**Issue by miroslavliska** [slovak-egov/nkod-portal#135]
Otvoril som si detail aplikácie, ktorú vytvoril iný používateľ ako ja, a tlačítko vymazať jeho pokusný komentár bolo stále možné použiť, čím som vymazal jeho komentár, čo považujem za chybu, pretože zmazať by sa mal dať len komentár, ktorý som vytvoril ja. 

A ak existuje komentár, ktorý odpovedá na môj komentár, tak by sa mazať už nemalo dať, maximálne ho editovať.

**Comment by elazenga** [comment]
Ano, ak je SuperAdmin
