### ISSUE TITLE
Nie je možné podať podnet MIRRI (chýba v zozname)

### ISSUE THREAD

**Issue by miroslavliska** [slovak-egov/nkod-portal#138]
V zozname poskytovateľov, ktorým sa podáva podnet musia byť všetci poskytovatelia z data.slovensko.sk. Chýba napr. MIRRI, ktoré treba doplniť a zoznam prekontrolovať.

**Comment by elazenga** [comment]
Netyka sa subsystemu ODKomunita, co dostaneme, to zobrazime
