### ISSUE TITLE
Oprava príliš skorého zalamovania názvu datasetu kvoli likom a komentárom

### ISSUE THREAD

**Issue by miroslavliska** [slovak-egov/nkod-portal#147]

**Comment by elazenga** [comment]
Opravene (aj na Aplikaciach a Podnetoch) na pomer 3/4 (nazov datasetu) k 1/4 (piktogramy). Je to maximum dany CSS stylmi ID-SK, ak je potreba to este zmenit, tak to si bude vyzadovat komplexnejsiu upravu.
