### ISSUE TITLE
Analýza vyhľadávania a jeho zlepšenie

### ISSUE THREAD

**Issue by lk8w** [slovak-egov/nkod-portal#15]
Vyhľadávanie funguje inak ako pri starom portáli (neviem či horšie alebo lepšie?), starý portál nájde pri zadaní „cestovný ruch“ 14 datasetov, nový len 5; „faktúry“ 147 vs. 10

**Comment by miroslavliska** [comment]
Toto je potrebné ešte viac analyzovať a nájsť konkrétne požiadavky na vyhľadávanie.

**Comment by lk8w** [comment]
Toto je celkom podstatná vec ale je to na tebe :)

**Comment by miroslavliska** [comment]
> Toto je celkom podstatná vec ale je to na tebe :)

No však ak to zanalyzujeme a presne určíme v čom je problém, tak to môžeme dať ešte realizovať. Kým to nemáme, tak to neviem posunúť na implementáciu.

**Comment by hornik-informo** [comment]
Tento task navrhujem posúdiť, až budeme maž reálne dáta na migráciu. Potom sa uvidí, čo dostaneme, akej kvalite, čo sa dá prebrať a čo nie.

**Comment by miroslavliska** [comment]
@lk8w podľa mňa tento task sa môže uzavrieť ,pretože v rámci M4 sa zlepšilo na dostatočnú úroveň. Si za, alebo máš ešte nejaké konkrétne pripomienky?

**Comment by lk8w** [comment]
Myslím že dobre funguje vyhľadávanie v názve datasetu a popise, to je základ. Takže za mňa je to momentálne dostačujúce.
Do budúcnosti by som dal ešte námet na zlepšenie - vyhľadávanie v názve distribúcie a vyhľadávanie konkrétneho názvu datasetu, ak ho dáš do úvodzoviek.
