### ISSUE TITLE
Odstránenie "Podnety na zverejnenie údajov" z pätičky portálu

### ISSUE THREAD

**Issue by MarkySim** [slovak-egov/nkod-portal#150]
Podnety už majú svoju vlastnú časť na portáli, prelink na metodický portál nie je potrebný (https://wiki.vicepremier.gov.sk/pages/viewpage.action?pageId=146573741), podnety boli premigrované do časti "podnety" na data.slovensko

**Comment by jozefhornik** [comment]
Odkaz bol odstránený.
