### ISSUE TITLE
Nefunkčnosť pridania podnetu/aplikácie/komentára pri prihlásení cez eID

### ISSUE THREAD

**Issue by lk8w** [slovak-egov/nkod-portal#151]

**Comment by lk8w** [comment]
Problém by mal byť v tom, ze pri pridaní podnetu sa zverejňuje e-mail a ak používateľ v slovensko.sk nemá e-mail tak to neprebehne. Malo by sa to prerobiť aby sa zverejňovalo meno, ktoré tam má každý.

**Comment by hornik-informo** [comment]
Bola navrhnutá zmena, podľa ktorej bude ako autor podnetu, aplikácie a komentára uvedené celé meno autora, kedže e-mailová adresa z ÚPVS nie je garantovane poskytovaná.

Úloha sa rozdelila na  časti:
1. Úprava IAM
2. Úprava Frontendu (React/TS)
3. Úprava Backend CMS (Piranha)

Všetky časti boli upravené a nasadené. Pôvodné podnety a aplikácie zostali s uvedením e-mailovej adresy, tie môžeme premigrovať, ak to je potrebné. Nové podnety, aplikácie, komentáre budú už uvedené s menom autora.

**Comment by hornik-informo** [comment]
Ďakujeme za nahlásenie. Máte pravdu, doteraz bolo stanovené, že s eID sa môže prihlásiť len zástupca poskytovateľa dát. Teraz už môže aj komunitný používateľ. Môžete, prosím, vykonať odhlásenie a nové prihlásenie a zadať Váš podnet?

**Comment by luciajanikova** [comment]
Už sa podarilo, vďaka https://data.slovensko.sk/podnet/fe56b48b-271e-41cf-9d35-70e631078af7.
