### ISSUE TITLE
Pre niektore formaty sa zobrazuje ikonka, pre niektore nie

### ISSUE THREAD

**Issue by miroslavliska** [slovak-egov/nkod-portal#21]
Toto treba zladit. Pre niektore vidim ikonku formatu, inokedy nie. 
Idealne by bolo, aby sa ta ikonka zobrazovala automaticky s nazvom formatu a predvolenou farbickou. Cize netreba riesit konkretne ikonky kokretnych formatov zvlast.

![image](https://github.com/slovak-egov/nkod-portal/assets/37801000/73fa9266-5c96-4e33-9a77-7c53b40c4ac6)

**Comment by hornik-informo** [comment]
Môžeme ikonky generovať, ale formáty majú aj dlhé názvy, takže maximálne 3 znaky z názvu formátu.
Prosím, aby sa zmenil míľnik na M3, keďže ten už nie je možné pripomienkovať.

**Comment by hornik-informo** [comment]
Vo vývojovej verzii je to zapracované. Názvy z číselníka ale nie sú úplne intuitívne. Číselník je možné upraviť bez zásahu do kódu.

![image](https://github.com/slovak-egov/nkod-portal/assets/144911183/fbbfb5ac-49bd-4296-ae77-0745e5bcd2b8)
