### ISSUE TITLE
Profil poskytovateľa dát sa neuloží. 

### ISSUE THREAD

**Issue by miroslavliska** [slovak-egov/nkod-portal#23]
Tento issue môže súvisieť s IAMkom. 
Po vyplnení a uložení údajov, a opätovnom načítaní stránky s profilom, dané údaje sa stratia.

**Comment by hornik-informo** [comment]
To je len problém práv, lebo testovací obsah nevznikol na portáli priamo, ale bol tam len skopírovaný. Aktuálne to už ide.

Tieto funkcionality sú testované automatizovane podľa testov: https://github.com/slovak-egov/nkod-portal/tree/main/src/Frontend.Test

**Comment by hornik-informo** [comment]
Toto issue považujem za dávno vyriešené (ešte 23.11.).

**Comment by miroslavliska** [comment]
OK, pretestoval som to na našom MIRRI profile.
