### ISSUE TITLE
Nezarovnanie v tabuľke lokálnych katalógov spôsobuje prekrývanie hodnôt

### ISSUE THREAD

**Issue by miroslavliska** [slovak-egov/nkod-portal#24]
![image](https://github.com/slovak-egov/nkod-portal/assets/37801000/beba7fa6-ff13-4d63-9b71-448aa077ae27)

**Comment by hornik-informo** [comment]
Explicitne sme nastavili zalamovanie dlhých slov, ale nemôžeme ho aplikovať na celý web, keďže šablóna (IDSK) nie je naša a mohlo by to znefunkčniť niektoré časti.

![image](https://github.com/slovak-egov/nkod-portal/assets/144911183/696966aa-65a0-476d-a329-9bf1df9e7441)

**Comment by miroslavliska** [comment]
OK, zatváram.
