### ISSUE TITLE
Chybné zobrazovanie ikony nasledujúcej stránky

### ISSUE THREAD

**Issue by lk8w** [slovak-egov/nkod-portal#28]
Na adrese: https://wpnkod.informo.sk/kvalita-metadat sa chybne zobrazuje ikona nasledujúcej stránky

![obrázok](https://github.com/slovak-egov/nkod-portal/assets/149062360/3e8d62a5-2466-4291-9acb-4edd1bcba54f)

**Comment by miroslavliska** [comment]
OKi, dakujem. Zaradujem to do M4.

**Comment by jozefhornik** [comment]
Tento task bol vyriešený.
