### ISSUE TITLE
Fazetové vyhľadávanie nad LKODmi

### ISSUE THREAD

**Issue by miroslavliska** [slovak-egov/nkod-portal#3]
Nad zoznamom LKOD je potrebné poskytnúť fazetové vyhľadávanie podľa:
- Poskytovateľa
- Typu lokálneho katalógu { DCAT-AP Dokumenty, SPARQL Endpoint, CKAN}

**Comment by hornik-informo** [comment]
Táto požiadavka bola zapracovaná do vývojovej verzie v okóbri.
