### ISSUE TITLE
Naharvestované datasety nevie webový portál podľa názvu nájsť

### ISSUE THREAD

**Issue by miroslavliska** [slovak-egov/nkod-portal#30]
Napr. naharvestovaný dataset Zvolena
![image](https://github.com/slovak-egov/nkod-portal/assets/37801000/72102849-936a-4c1b-a84f-4a6fb08c19f7)

sa nenájde prostredníctvom vyhľadávania
Uvedený dataset nie je vo výsledku.
![image](https://github.com/slovak-egov/nkod-portal/assets/37801000/568800ab-a0ea-42d0-b00d-2b9dbba43b8e)

**Comment by jozefhornik** [comment]
Harvestovanie ešte neprebieha pomocou registrácii z portálu, preto sa v ňom nemôžu zobraziť datasety.
