### ISSUE TITLE
Vo fazetovom vyhľadávaní chýba poskytovateľ datasetu z lokálneho katalógu

### ISSUE THREAD

**Issue by miroslavliska** [slovak-egov/nkod-portal#31]
Aj keď sa naharvestovali datasety z nejakého lokálneho katalógu, napr. mesta Zvolen, 
ktoré má URI <https://data.gov.sk/id/legal-subject/00320439>

tak tento poskytovatel datasetu nie je vo vyhľadávaní.

**Comment by hornik-informo** [comment]
Vo fazetovom vyhľadávaní poskytovateľ je, ale stále má portál oddelené registrácie od harvestera. Na tom ideme popracovať.

**Comment by miroslavliska** [comment]
> Vo fazetovom vyhľadávaní poskytovateľ je, ale stále má portál oddelené registrácie od harvestera. Na tom ideme popracovať.

Súhlasím, toto môžeme implementovať bez čakania na odstavenie harvestácie z data.gov.sk

V pipeline [03 - Harvestace LKOD a registrací](https://github.com/datova-kancelaria/nkod-sk/raw/main/screenshoty/03.webp
)

sa nastavujú na začiatku adresáre, odkiaľ sa berú dané zdrojové súbory. Je to:
/data/registration/repository/poskytovatelé
/data/registration/repository/lkody

Niekde ale musí existovať skript, ktorý kopíruje registrácie poskytovateľov a lkodov z githubu do týchto adresárov. Toto musím zistiť, kde sa to deje.
