### ISSUE TITLE
Chýbajúce údaje v detaili - LKODu

### ISSUE THREAD

**Issue by miroslavliska** [slovak-egov/nkod-portal#4]
V detaili LKODu chýbajú nasledovné informácie
- Meno a priezvisko kontaktnej osoby
- Email kontaktnej osoby
- Typ lokálneho katalógu
- URL pre LKOD API
- Pre každú distrubúciu je potrebné zobraziť infomrácie o právach použitia. (Toto sa dá otestovať na naharvestovaných datasetoch, tam tie dáta sú.)
- Názov a domovská stránka sú už detaili.

**Comment by miroslavliska** [comment]
Pridávam ešte informáciu o Podmienkach použitia pre každú distribúciu.

**Comment by hornik-informo** [comment]
Požiadavka je zapracovaná vo vývojovej verzii. 

Zobrazovanie informácií o distribúciách nebolo súčasťou M2, ale môžu sa vyriešiť v rámci M4. Bolo by ale dobré pre ňu zriadiť samostatné issue, keďže sa netýka LKOD.
