### ISSUE TITLE
Pri zmene počtu zobrazených výsledkov (10,20, 50) sa nezobrazí nič

### ISSUE THREAD

**Issue by miroslavliska** [slovak-egov/nkod-portal#49]
Príklad: zmenil som počet na 50, a riadky s výsledkami sa zrazu stratili.
![image](https://github.com/slovak-egov/nkod-portal/assets/37801000/064dc181-11bd-4888-810b-6d97933134b7)

**Comment by jozefhornik** [comment]
Na piatej strane po 50 zo 166 výsledkov nemôže byť nič, ale upravili sme to tak, aby po zmene veľkosti stránky bol používateľ presmerovaný na prvú stránku.
