### ISSUE TITLE
Zobrazovanie ikoniek indikujúcich chýbajúcu kvalitu

### ISSUE THREAD

**Issue by miroslavliska** [slovak-egov/nkod-portal#5]
V prípade, ak dataset obsahuje
- distribúciu, ktorá je označená že sa nedá stiahnuť, 
- nevyplnené podmienky použitia datasetu

zobrazí sa informačná ikonka (warning) s popisom daného problému.

**Comment by hornik-informo** [comment]
Táto požiadavka nebola zahrnutá v M2 a žiadala by zmenu spojenia Frontendu na SPARQL rozhranie. Môžeme to vytvoriť v rámci M4.

**Comment by miroslavliska** [comment]
Top prioritná požiadavka, zaraďujem do SLA.

**Comment by hornik-informo** [comment]
Na teste je sprístunená funkcionalita. Varovanie na dostupnosť súborov je získavané z harvestra z produkcie, takže nie všetky nedostupné súbory majú túto informáciu dostupnú. Príklad nedostupného súboru je tu:
https://wpnkod.informo.sk/datasety/b75c4a11-dd90-3614-c355-c71ef8646820

![image](https://github.com/slovak-egov/nkod-portal/assets/144911183/ed3ddc02-a165-40ea-8bc8-4a75c865d73c)


![image](https://github.com/slovak-egov/nkod-portal/assets/144911183/0cdc13b9-a2f3-47ec-910d-3f5eb1869767)

**Comment by lk8w** [comment]
Toto vyzerá že funguje, len upozorňujem na súbory, ktoré je možné stiahnuť ale sú vykazované ako nestiahnuteľné (tento problém je v samotných reportoch ktoré sa každý deň generujú v linkedpipes). Napr. https://wpnkod.informo.sk/datasety/ca4cb74c-7192-4198-b074-34acd9d295e7

**Comment by hornik-informo** [comment]
Issue bolo nasadené do produkcie.

**Comment by sunderlikova** [comment]
Potvrdenie nasadenia.
