### ISSUE TITLE
Stránkovanie vo výsledkoch musí byť spracované rovnako ako stránkovanie v datasetoch pre poskytovateľa

### ISSUE THREAD

**Issue by miroslavliska** [slovak-egov/nkod-portal#50]
Stránkovanie vo výsledkoch nedokáže poskytnúť možnosť skoku na koniec zoznamu, ale je treba postupne prechádzať jednotlivými stránkami. To je nepoužiteľné.

![image](https://github.com/slovak-egov/nkod-portal/assets/37801000/b89bf8d2-c030-4ce4-91d3-e2542ba3f81b)

Je to potrebné spraviť ako pri stránkovaní datasetov, ktoré spravuje poskytovateľ, tj.

![image](https://github.com/slovak-egov/nkod-portal/assets/37801000/f0b0bf7c-b7c5-4617-a2e8-b20f7eb30b02)

S tým súvisí aj požiadavka, aby boli oba tieto stránkovacie komponenty zarovnané rovnako - napravo.

**Comment by jozefhornik** [comment]
Výsledky vyhľadávania sú spracované podľa vzoru IDSK
https://idsk.gov.sk/vzory/vzor-search
