### ISSUE TITLE
Pri uložení datasetu vznikne údaj dcat:issued, pri jeho aktualizácii je to dct:modified

### ISSUE THREAD

**Issue by miroslavliska** [slovak-egov/nkod-portal#51]
Je potrebné, aby aplikácia pri každom vytvorení alebo aktualizácií, ukladala tieto metadáta.

**Comment by hornik-informo** [comment]
Ešte dávam na zváženie, či dátum aktualizácie datasetu nemeniť aj pri zmene distribúcie. Teda napr. dnes pridám dataset a zajtra do neho pridám distribúciu.

**Comment by miroslavliska** [comment]
> Ešte dávam na zváženie, či dátum aktualizácie datasetu nemeniť aj pri zmene distribúcie. Teda napr. dnes pridám dataset a zajtra do neho pridám distribúciu.

Ano, suhlasim.

**Comment by hornik-informo** [comment]
Upravené tak, aby pri zmene distribúcie bol aktualizovaný čas modifikácie datasetu.
