### ISSUE TITLE
Nefunkčnosť rozbaľovania/zbaľovania filtra

### ISSUE THREAD

**Issue by lk8w** [slovak-egov/nkod-portal#56]
Nejde mi rozbaliť a zbaliť ostatné filtre (napr. formát, kľúčové slovo), funguje mi to len pri filtrovaní poskytovateľov dát.

Firefox 120.0.1 64bit

![obrázok](https://github.com/slovak-egov/nkod-portal/assets/149062360/a1170843-43dc-418f-b587-3090aaf31707)
![obrázok](https://github.com/slovak-egov/nkod-portal/assets/149062360/d5e4b99a-eba0-49e6-860f-55291d7625b2)

**Comment by jozefhornik** [comment]
Môžem potvrdiť, že to niekedy nefunguje, ale nie vždy. Túto funkciu zabezpečuje ID-SK a upravíme to tak, aby to fungovalo vždy, prinajhoršom tie funkcie prevezmeme do nášho kódu.

![image](https://github.com/slovak-egov/nkod-portal/assets/66019378/b42af77a-4c0a-4687-b42c-89ed6d3c97f8)

**Comment by hornik-informo** [comment]
Nasadili sme upravenú verziu s opravou.
Poznámka pre budúcnosť: ak by sa ukázalo ako problém, tak bude lepšie prebrať funkcie, ktoré poskytuje idsk do kódu portálu (definované v @id-sk\frontend\idsk\all.js). ID-SK nie je v tejto chvíli úplne vhodné na dynamický obsah, ako je SPA webový portál NKOD.

**Comment by miroslavliska** [comment]
@lk8w  prosim ta, je tento task z tvojho pohladu vyrieseny?

**Comment by lk8w** [comment]
áno
