### ISSUE TITLE
Nefunkčnosť vyhľadávania lokálne katalógy

### ISSUE THREAD

**Issue by lk8w** [slovak-egov/nkod-portal#59]
https://data.slovensko.sk/lokalne-katalogy

Vyhľadať výraz "grafu". 
Nájde 1 výsledok.
Vymazať "grafu".
Vyhľadať výraz "grafu". 
Nájde 0 výsledkov.

Prosím o otestovanie. Niekedy mi to nenájde na 1. krát, niekedy až na 2.

**Comment by hornik-informo** [comment]
Viete to, prosím, overiť znovu? Môže to byť len tým, že jedno vyhľadávanie predbehne druhé a to sme upravili.

**Comment by lk8w** [comment]
Dobrý deň, testoval som to teraz doma a bude to najskôr spôsobené menej kvalitnou wifi, na ktorej som bol predtým pripojený.
