### ISSUE TITLE
Nefunkčnosť vyhľadávania dataetov pre špecifické prípady 

### ISSUE THREAD

**Issue by lk8w** [slovak-egov/nkod-portal#60]
https://data.slovensko.sk/datasety

Vyfiltrovať formát XML a poskytovateľa dát mesto Prešov.
Vyhľadať výraz "občanov".
Nájde 1 výsledok.
Vymazať "občanov".
Vyhľadať výraz "občanov".
Nájde 0 výsledkov.

Prosím o otestovanie. Niekedy mi to nenájde na 1. krát, niekedy až na 2.

**Comment by hornik-informo** [comment]
Viete to, prosím, overiť znovu? Môže to byť len tým, že jedno vyhľadávanie predbehne druhé a to sme upravili.

**Comment by lk8w** [comment]
Dobrý deň, testoval som to teraz doma a bude to najskôr spôsobené menej kvalitnou wifi, na ktorej som bol predtým pripojený.

**Comment by miroslavliska** [comment]
OK, tento task zatváram.
