### ISSUE TITLE
Zarovnanie poskytovateľa dát

### ISSUE THREAD

**Issue by lk8w** [slovak-egov/nkod-portal#61]
Toto je skôr designová vec, ale prečo v niektorých prípadoch je zarovnanie doľava? Asi to súvisí s tým že chýba distribúcia ale aj tak si myslím ze by to malo byť stále vpravo pre prehľadnosť.

![obrázok](https://github.com/slovak-egov/nkod-portal/assets/149062360/c2f4e578-3c55-409d-858b-bd718ed4e724)

**Comment by hornik-informo** [comment]
Vľavo sa zobrazujú odkazy na distribúcie a tento dataset žiadne nemá. Môžeme pri finálnom importe 2. februára tieto datasety schovať, nech sa nezobrazujú.

**Comment by lk8w** [comment]
OK, toto skúste prejsť s Mirom Líškom či je to OK a ak to tak bude tak by to malo byť jasne napísané v dokumentácii, že datasety bez distribúcií sú skryté.

**Comment by miroslavliska** [comment]
> OK, toto skúste prejsť s Mirom Líškom či je to OK a ak to tak bude tak by to malo byť jasne napísané v dokumentácii, že datasety bez distribúcií sú skryté.

Navhujem jednoduchú funkcionalitu, že kým nemá dataset distribúciu, tak sa mu nedovolí nastaviť dataset na publikáciu (máme hodnoty nepublikovaný a publlikovaný). mohla by byť tam chybova hlaska, ze - Najskor pridajte distribúciu, ak chcete mat dataset zverejnený.

**Comment by hornik-informo** [comment]
Na portáli to je tak, že dataset bez distribúcií je nepublikovaný automaticky, ale tieto situácie vznikali importom, pretože tie dáta nevznikli v rámci portálu.

**Comment by miroslavliska** [comment]
OK, toto zatváram.
