### ISSUE TITLE
Datasety patriace do dátovej série sa nezobrazia

### ISSUE THREAD

**Issue by miroslavliska** [slovak-egov/nkod-portal#62]
Napr. tento zdrojový dataset v data.gov.sk
https://data.gov.sk/dataset/3c140c76-4252-4dea-ae9f-2fb030a50171

obsahuje distribúcie, ktoré sa po harvestácií stanú datasetmi, zastrešené špeciálnym datasetom typu dátová séria:
https://data.slovensko.sk/datasety/04336071-5beb-4b5c-8034-6a674d87ea64

Reálne má tento dataset URI
https://data.gov.sk/set/3c140c76-4252-4dea-ae9f-2fb030a50171

a keď is vypýtam všetky vlastnosti tohto datasetu cez SPARQL Endpoint, tak vidím, že sú tam aj vzťahy na jeho podradené datasety
```
PREFIX dcat: <http://www.w3.org/ns/dcat#>
SELECT *
WHERE {
  <https://data.gov.sk/set/3c140c76-4252-4dea-ae9f-2fb030a50171> ?p ?o .
}
```
![image](https://github.com/slovak-egov/nkod-portal/assets/37801000/ec59716a-99e0-46da-95c7-663658e386c4)

ale na frontende to nevidno!
![image](https://github.com/slovak-egov/nkod-portal/assets/37801000/30f5853e-09bb-497d-b6cf-ad20f0d935f6)

**Comment by hornik-informo** [comment]
Zmena bola nasadená.

https://data.slovensko.sk/datasety/3c140c76-4252-4dea-ae9f-2fb030a50171

![image](https://github.com/slovak-egov/nkod-portal/assets/144911183/405675ab-6ff9-404f-96f4-17eb04c07fae)

**Comment by miroslavliska** [comment]
OK, uzatvaram.
