### ISSUE TITLE
URL datasetov musí používať rovnaký hashovací kód ako v starom portáli

### ISSUE THREAD

**Issue by miroslavliska** [slovak-egov/nkod-portal#63]
V starom portáli existuje má tento dataset URI
https://data.gov.sk/dataset/3c140c76-4252-4dea-ae9f-2fb030a50171

v novom však má adresu
https://data.slovensko.sk/datasety/04336071-5beb-4b5c-8034-6a674d87ea64

je potrebné, aby aj v novom portáli bol použitý rovnaký kód, tj. 
https://data.slovensko.sk/datasety3c140c76-4252-4dea-ae9f-2fb030a50171

Tento atribút už má dataset naharvestovaný, v dct:identifier

**Comment by hornik-informo** [comment]
Zmena bola nasadená.

**Comment by miroslavliska** [comment]
Potvrdzujem funkcnost.
