### ISSUE TITLE
Čitateľné URI pre dataset (dcat:landingPage) sa nekontroluje na jedinečnosť

### ISSUE THREAD

**Issue by miroslavliska** [slovak-egov/nkod-portal#65]
Každý dataset, ktorý bude mať nejaké systémové URI, ktoré sa vytvorí pri uložení, môže mať nastavenú aj čitateľnú formu URI. 
Tj. frontend pri detaile nového datasetu umožní doplniť čitateľnú formu URI, ktorá nesmie existiovať. Pred uložením sa musí skontrolovať, či také niečo už neexistuje. 

Napr. keď budem vytvárať dataset faktúr MIRRI, tak okrem keĎ zaevidujem jeho názov - 
"Faktúry MIRRI 2024-02", budem mať možnosť doplniť jeho čitateľnú URI
https://data.gov.sk/set/faktury-mirri-2024-02. 

Keď sa toto implementuje na GUI, tak by to malo fungovať automaticky, nakoľko bude existovať dereferenciácia z 

- data.gov.sk/dataset/* na data.slovensko.sk/datasety/*, a aj
- data.gov.sk/set/* na data.slovensko.sk/datasety/*

Táto vlastnosť sa bude ukladať do dcat:landingPage. Toto sa pridá aj do DCAT-AP-SK2.0

**Comment by miroslavliska** [comment]
> Zvážite možnosť, že by čitateľné URI generoval portál sám bez možnosti úpravy?

V starom portáli je to spravené takto: 

Štandardne čitateľné URI datasetu (dcat:langingPage) sa odvodzuje od názvu datasetu. Ako používateľ píše, tak vzniká URI datasetu
![image](https://github.com/slovak-egov/nkod-portal/assets/37801000/fa74cc59-7335-44a8-a21b-82c3b1c88942)

avšak je ho možné v prípade potreby zmeniť:
![image](https://github.com/slovak-egov/nkod-portal/assets/37801000/2ca1d4b0-1ceb-49f1-8ac9-9c2c17a35888)

Ideálne by bolo zachovať tento mechanizmus.

**Comment by hornik-informo** [comment]
Znamená to, že nebude možné vložiť iné dcat:landingPage ako https://data.gov.sk/dataset/*? Pretože už datasety LKODov to majú inak podľa #64.

**Comment by miroslavliska** [comment]
> Znamená to, že nebude možné vložiť iné dcat:landingPage ako https://data.gov.sk/dataset/*? Pretože už datasety LKODov to majú inak podľa #64.

dcat:langingPage vzniknuty z harvestacie bude vtedajsia citatelna URL stranka. po skonceni data.gov.sk sa uz nebudu datasetom pridelovat uricka typu https://data.gov.sk/dataset, ale len data.gov.sk/set/, cize v novom systeme sa bude citatelne URI robit z textu vlozeneho za posledne lomitko: 
https://data.gov.sk/set/**faktury-2023-06**

pre naharvestovane datasety z lkodov bude landingPage nasmerovane detail datasetu v ich domovskom portali, ak vobec nejaky opendata portal maju. inak bude prazne. URI bude ale stale https://data.gov.sk/set/*
cize z pohladu frontendu to bude URL stranka, ktora by sa mohla otvorit v novom okne.

**Comment by hornik-informo** [comment]
Nie je to nemožné, ale je to potencionálne v konflikte s tým, že datasety majú IRI https://data.gov.sk/set/guid a bola požiadavka, aby to zároveň tiež služilo ako presmerovanie na detail datasetu.

Teraz majú datasety čitateľné URL vo formáte http://HOST/dataset/nazov-datasetu a to by mohlo ostať zachované, teda aj nové datasety budú dosiahnuteľné adresou /dataset/nazov-datasetu. Značne by to komplikovalo editáciu datasetov, lebo staré by mali niečo iné ako nové.

LKODy spomínam preto, lebo majú mať možnosť ľubovolného landingPage, čo 
a) sa može dostať do konfliktu s tým, že si navolia niečo, čo už data.slovensko.sk používa pre svoju potrebu
b) sú editovateľné cez Správu datasetov a tá podľa vzoru starého portálu má možnosť voliť len URL slug (pod https://data.slovensko.sk/dataset/*), a pritom budú mať landingPage úplne s iným názovom hosta (napr. https:///opendata.mfsr.sk/dataset/nieco).

**Comment by hornik-informo** [comment]
Navrhujeme, aby pre nový dataset bol automaticky vytvorený slug z názvu (zlozene ako pismena, cisla a jednoduchej pomlcky), pomocou ktoreho sa bude dať referencovať dataset adresou https://data.slovensko.sk/datasety/****. Používateľ bude mať možnosť vložiť svoj vlastný text, pre ktorý sa overí dostupnosť pri uložení datasetu. Hodnota sa z dôvodov kompatibility uloží ako dcat:landingPage s prefixom https://data.gov.sk/dataset/*** - aby to bolo v rovnakom tvare ako doterajšie datasety.

V prípade otvorenia editácie importovaného datasetu sa sprístupné len možnosť editácie celej hodnoty atribútu dcat:landingPage, pretože tá môže byť v úplne inom tvare mimo hosta data.gov.sk.

**Comment by hornik-informo** [comment]
Ukladať sa tieto informácie budú v tvare https://data.gov.sk/set/xxxxx a adresy v tomto tvare budú aj prezetované verejnosti. Príklad takej adresy: https://data.gov.sk/set/faktury-mirri-2023

**Comment by miroslavliska** [comment]
> Ukladať sa tieto informácie budú v tvare https://data.gov.sk/set/xxxxx a adresy v tomto tvare budú aj prezetované verejnosti. Príklad takej adresy: https://data.gov.sk/set/faktury-mirri-2023

Ano, to je spravne. /dataset/ je pre nas historicky. 
Tu mozete vidiet pravidla pre URI, podla metodiky data.gov.sk URI
https://wiki.vicepremier.gov.sk/pages/viewpage.action?pageId=1641682

**Comment by miroslavliska** [comment]
@hornik-informo  toto by som navrhol riešiť možno jednoduchšie cez len kontrolu, či už v NKODe takáto URL je voľná. Napr. vyskúšal som vložiť už použitú URL z iného datasetu
![image](https://github.com/slovak-egov/nkod-portal/assets/37801000/5f1e086a-33c6-440b-80cc-81a02cb91cd5)

a mal by som dostať minimálne chybu, že "Dataset s takouto domovskou stránkou v NKODe už existuje".

**Comment by hornik-informo** [comment]
Kontrola duplicity bola nasadená.
