### ISSUE TITLE
Zabezpečenie dereferenciácií z data.gov.sk na data.slovensko.sk

### ISSUE THREAD

**Issue by miroslavliska** [slovak-egov/nkod-portal#66]
Pre správne fungovanie data.slovensko.sk je potrebné nastaviť nasledovné tri dereferenciácie:

- [x] data.gov.sk -> data.slovensko.sk
- [x] data.gov.sk/dataset/* -> data.slovensko.sk/datasety/*
- [x] data.gov.sk/set/* -> data.slovensko.sk/datasety/*

**Comment by hornik-informo** [comment]
Zapracované, v tejto chvíli nasadené na teste, pretože tam sú dáta s potrebnými meta.

Pre data.gov.sk/set/a1d232ee-a594-4f24-8114-13a014619157 bude používateľ presmerovaný na https://data.slovensko.sk/set/a1d232ee-a594-4f24-8114-13a014619157 a teda v prípade testu sem: 
http://nkod.mirri.tech/set/a1d232ee-a594-4f24-8114-13a014619157

Po ovorení data.gov.sk/dataset/plodiny-sr bude presmerovaný na https://data.slovensko.sk/dataset/plodiny-sr a teda v prípade testu sem:
http://nkod.mirri.tech/dataset/plodiny-sr
