### ISSUE TITLE
Chýba funkcionalita pridanie nového poskytovateľa

### ISSUE THREAD

**Issue by miroslavliska** [slovak-egov/nkod-portal#67]
Momentálne mám možnosť len odstrániť, resp. upraviť poskytovateľa, ale chýba možnosť pridať nového.
![image](https://github.com/slovak-egov/nkod-portal/assets/37801000/0dd41f95-ff01-4739-b338-99d81b10b73d)

Štruktúra musí byť v nasledovnom tvare, ako je na githube:
Toto je MFSR
https://github.com/datova-kancelaria/nkod-registrace/blob/develop/poskytovatel%C3%A9/00151742.ttl

Potrebujem názov, ičo a právnu formu.

**Comment by hornik-informo** [comment]
Podľa DNR sa poskytovatelia registrujú sami. Teraz keď existujú pozvánky tak už táto funkcionalita dáva zmysel. 
Je ale potrebná právna forma? Ak áno, tak ju bude potrebné pridať aj do registrácie.

**Comment by miroslavliska** [comment]
> Podľa DNR sa poskytovatelia registrujú sami. Teraz keď existujú pozvánky tak už táto funkcionalita dáva zmysel. Je ale potrebná právna forma? Ak áno, tak ju bude potrebné pridať aj do registrácie.

Pravna forma je dolezita. Okrem Ministerstiev resp. (OVM) sa pocita aj so zapojenim akademickych subjektov, obcianskych zdruzeni, neziskovych organizacii. Je to podla odporucani EU. Hned ako zvladneme preniest tych, ktorych pouzivaju stare data.gov.sk tak sa zameriame aspon na par novych subjektov.

Moja predstava je, ze Superadministrator moze pridat noveho poskytovatela a tam nastavim pravnu formu. Pozvanky sa budu robit ako doteraz, ci uz manualne alebo automaticky. Toto musim tiez pohnut.

**Comment by miroslavliska** [comment]
Ešte by som poprosil tu pridať tu filter, pretože často musím stránkovať, kým nájdem hľadaný subjekt.

**Comment by miroslavliska** [comment]
Pretestoval som to, je to OK .Telegonne číslo kontaktnej osoby prosím nastaviť ako nepovinná hodnotu.

**Comment by hornik-informo** [comment]
Telefón je už nepovinný.
