### ISSUE TITLE
Pridanie kalendárika pre možnosť vybrať si dátumový údaj

### ISSUE THREAD

**Issue by miroslavliska** [slovak-egov/nkod-portal#68]
Pri zadávaní formátu, aj pri jeho zobrazení na frontende treba používať jediný validný formát dátumu a to YYYY-MM-DD .
Môžem ho takto môžem zadať, no keď ho znova editujem, tak vidím formát MM/DD/YYYY.

**Comment by miroslavliska** [comment]
> Nebolo by intuitívnejšie ponechať vkladanie a zobrazovanie dátumov v bežnom formáte? Do RDF súborov sú vkladané vo formáte YYYY-MM-DD.

My v dátovke celý čas (cca posledné tri roky), či už na pracovniých skupinách alebo v štandardoch prefereujeme používanie strojovo-spracovanteľného dátumu a času podľa štandardu XSD, tj. YYYY-MM-DD. Čiže nejde o špeciálny štandard RDF.
https://www.w3schools.com/xml/schema_dtypes_date.asp

Ako najlepšie riešenie navrhujem pridať utliliu kalendár (vo vyskočenom okne), v ktorom sa vyberie dátum. Týmto spôsobom by nemal byť problém, aj keď by vo frontende mal byť iný formát ako XSD.

**Comment by hornik-informo** [comment]
Potrebujeme sa uistiť, že teda ostávame pri súčasnom stave, že prezentované a editované dátumy sú v intuitívnom fomáte a ukladajú sa podľa štandardu. Potom stačí len pridať kalendárik.

![image](https://github.com/slovak-egov/nkod-portal/assets/144911183/e9177d34-1d13-41d6-9824-bef52b9ba349)

**Comment by miroslavliska** [comment]
OK, môže to tak byť. Ten kalendárik je ale potrebné k tomu pridať. Lebo štandard DCAT-AP-SK2.0 sa pozerá celkom dosť, je to v podstate aj návod čo vypĺňať do GUI, a bude to podľa mňa dosť mýliť. Ľudia budú mať tendenciu skúšať tam vkladať xsd formát.

**Comment by hornik-informo** [comment]
Kalendárik bol pridaný do formulára.

**Comment by miroslavliska** [comment]
Otestovane, funguje.
