### ISSUE TITLE
Na GUI nie sú zobrazené všetky evidované údaje datasetu

### ISSUE THREAD

**Issue by miroslavliska** [slovak-egov/nkod-portal#69]
Pri zobrazení zaevidovaného datasetu, chýbajú zobrazené údaje
- typ datasetu
- odkaz na špecifikáciu datasetu
- domovská stránka datasetu (nahrádza dokumentáciu datasetu)
- priestorové rozlíšenie v metroch
- časové rozlíšenie
- dataset patrí do série (ak patrí dataset do nejakej série, tak tam musí byť odkaz na tento nadradený dataset)
- ďaľšie datasety z tejto série (tu má byť odkaz ďaľších datasetov z nadradenej série)

Poznámka: ak zobrazujem dataset typu dátová séria, tak v rámci jeho detailu sa zobrazuje text: Datasety z tejto série, nie text Dalšie datasety z tejto série.

**Comment by hornik-informo** [comment]
Zmena bola nasadená.
