### ISSUE TITLE
Na GUI nie sú zobrazené všetky evidované údaje distribúcie

### ISSUE THREAD

**Issue by miroslavliska** [slovak-egov/nkod-portal#70]
Nie je možné zobraziť si všetky zaevidované údaje distribúcie. Vidím len link na stiahnutie. Chýbajú:
- podmienky použítia distribúcií
- typ média na stiahnutie
- schéma

Tieto vlastnosti by bolo ideálne zobrazovať rozbalovaním. Tj. v základe je to tak ako to je teraz, po kliknutí na malú ikonku rozbaliť sa tam vložia uvedené chýbajúce hodnoty.

**Comment by hornik-informo** [comment]
Zapracované (v tomto momente nasadené na teste).

![image](https://github.com/slovak-egov/nkod-portal/assets/144911183/0d593c19-bf6d-4689-aaa6-5433242eb245)
