### ISSUE TITLE
Ak je dataset typu dátová séria, v zozname výsledkov je potrebné zobraziť malú ikonku reprezentujúcu sériu

### ISSUE THREAD

**Issue by miroslavliska** [slovak-egov/nkod-portal#71]
Niečo takéto:
https://www.shutterstock.com/image-vector/dataset-icon-multi-temporal-data-time-1316686355

**Comment by hornik-informo** [comment]
Zmena bola nasadená. 

![image](https://github.com/slovak-egov/nkod-portal/assets/144911183/45d62e15-b6ce-46d3-8635-f480ca0a8a5e)
