### ISSUE TITLE
Ak má dataset dátovou sériou a má podradené datasety, nie je ho možné zmazať

### ISSUE THREAD

**Issue by miroslavliska** [slovak-egov/nkod-portal#72]
Pri takejto akcii sa zobrazí informácia: Dátovú sériu nie je možné zmazať, najskôr prosím zmažte všetky datasety z tejto série.

**Comment by hornik-informo** [comment]
Zmena bola nasadená.

![image](https://github.com/slovak-egov/nkod-portal/assets/144911183/ceb57b01-0663-450a-8bcf-01fbe3966200)
