### ISSUE TITLE
Pridanie odkazu "Podnety na zverejnenie údajov" do pätičky v portáli

### ISSUE THREAD

**Issue by miroslavliska** [slovak-egov/nkod-portal#73]
Vedľa odkazu technická podpora v pätičke portálu, je potrebné pridať ďaľší odkaz: **Podnety na zverejnenie údajov**, ktorý otvorý nasledovnú stránku:
https://wiki.vicepremier.gov.sk/pages/viewpage.action?pageId=146573741

**Comment by hornik-informo** [comment]
Zmena bola nasadená.

![image](https://github.com/slovak-egov/nkod-portal/assets/144911183/a53d5a77-10dc-46b5-ad0f-35f7b8901428)
