### ISSUE TITLE
Pridanie vyhľadávacej fazety - typ poskytovateľa

### ISSUE THREAD

**Issue by miroslavliska** [slovak-egov/nkod-portal#75]
Datasety musí byť možné vyhľadávať aj podľa typu poskytovateľa. Národný katalóg otvorených dát slúži pre všetky subjekty, ktoré chcú publikovať otvorené údaje, tj. ministerstvá, mestá a obce, občianske združenia, privátny sektor, akademické subjekty a podobne. Do konca fázy M4 je plán pridať aspoň pár poskytovateľov z ďaľších oblastí, ako len Ministerstvá.

Fazeta - typ poskytovateľa bude umiestnená na prvom mieste, pred fazetou Poskytovateľ.

**Comment by hornik-informo** [comment]
Aký je zdroj dát pre tento filter?

**Comment by hornik-informo** [comment]
To je možné, ale ten číselník nie je veľmi intuitávny. Neviem, či má niekto záujem filtrovať subjekty podľa toho, či je to rozpočtová alebo príspevková organizácia.

**Comment by miroslavliska** [comment]
Ano, to je mozno pravda, ale pravna forma organizacie je zakladny referencny ciselnik, ktory sa dost casto pouziva. Neradi by sme pouzivali iny.

**Comment by miroslavliska** [comment]
Toto je určite dôležitý task, zaraďujem ho do implemetácie pre WNPNKOD-SLA

**Comment by hornik-informo** [comment]
Na teste sme sprístupnili filter, je závislý od toho, koľko poskytovateľov dát má vyplnený typ. 
https://wpnkod.informo.sk/datasety

**Comment by hornik-informo** [comment]
Issue bolo nasadené do produkcie.
