### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by lk8w** [slovak-egov/nkod-portal#76]
Bolo by fajn mať aj favicon (pre ľahšiu identifikáciu pre používateľov ktorí si portál uložia do záložiek).

![obrázok](https://github.com/slovak-egov/nkod-portal/assets/149062360/18cb37fc-2054-42bb-8657-d5e59f8a8864)

**Comment by miroslavliska** [comment]
Toto je dobry point, potrebujeme dat dokopy par navrhov a jeden vybrat.

**Comment by hornik-informo** [comment]
Favicon bol pridaný.

**Comment by miroslavliska** [comment]
Oki, vidím už ikonku pri portali. 
![image](https://github.com/slovak-egov/nkod-portal/assets/37801000/99c815c3-8c73-4ee2-826e-ccbf2a65c6b0)
Zatvaram task.
