### ISSUE TITLE
Zmena číselníkov licencií a vyhľadávania

### ISSUE THREAD

**Issue by hornik-informo** [slovak-egov/nkod-portal#77]
Vlastnosti distribúcií leg:authorsWorkType, leg:originalDatabaseType, leg:databaseProtectedBySpecialRightsType budú zdieľať jeden nový číselník licencií, ktorý bude zahŕňať licencie z pôvodného data.gov.sk. Vlastnosti leg:personalDataContainmentType zostáva pôvodný číselník.
Vo vyhľadávaní datasetov pribudnú 2 fazety:
-	Vyhľadávanie podľa licencií distribúcií (výber z nového číselníka)
-	Vyhľadávanie podľa stavu výskytu osobných údajov

Nový číselník licencií je potrebné ešte dodať.

Prosím o potvrdenie zadania.

**Comment by miroslavliska** [comment]
Potvrdzujem riesenie dohodnute na meetingu. Cielnik pre licencie je tu:
https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/licence

Subor na stiahnutie je tu:
https://op.europa.eu/o/opportal-service/euvoc-download-handler?cellarURI=http%3A%2F%2Fpublications.europa.eu%2Fresource%2Fcellar%2Fab0e79f8-5c6c-11ee-9220-01aa75ed71a1.0001.03%2FDOC_1&fileName=licences-skos.rdf

**Comment by hornik-informo** [comment]
Nasadené zatiaľ na teste.

**Comment by hornik-informo** [comment]
Medzičasom to bolo nasadené aj na produkcii.
