### ISSUE TITLE
Automatické vypĺňanie licencií pre druhú a nasledovných distribúcie datasetov

### ISSUE THREAD

**Issue by hornik-informo** [slovak-egov/nkod-portal#78]
V prípade zadávania druhej a nasledovných distribúcií datasetov sa do formulára novej distribúcie nakopíruje (pred vyplní) stav licencií podľa prvej vloženej distribúcie rovnakého datasetu. Tento stav môže používateľ zmeniť, ale predpokladá sa, že vo väčšine prípadov budú mať distribúcie rovnaký licenčný stav.

Prosím o potvrdenie zadania.

**Comment by miroslavliska** [comment]
Potvrdzujem riesenie. Takto sme sa dohodli aj na pracovnom stretnuti.

**Comment by hornik-informo** [comment]
Nasadené zatiaľ na teste.

**Comment by hornik-informo** [comment]
Medzičasom to bolo nasadené aj na produkcii.

**Comment by miroslavliska** [comment]
Ano potvrdzujem tento task, ale prosim este o dolezitu vec: Aby bola prednastavena vzdy hodnota 

http://publications.europa.eu/resource/authority/licence/CC_BY_4_0

nie ta prva polozka. K tomuto musime urobit vela suportnych materialov.

**Comment by hornik-informo** [comment]
Nastavili sme prednstavene licencie.
