### ISSUE TITLE
Modifikácia populárneho obsahu

### ISSUE THREAD

**Issue by lk8w** [slovak-egov/nkod-portal#8]
Do časti Populárny obsah dať namiesto súčasného obsahu (ktorý duplikuje hlavné menu) odkazy na HVD datasety, často sťahované datasety, žiadané datasety, kvalitné datasety, API (real-time data).

**Comment by miroslavliska** [comment]
Toto musíme ešte upresniť. V rámci verzie NKOD-23.12 nedokážeme urobiť často sťahované datasety, resp. kvalitné datasety, či API. Musíme to premyslieť. Viem si ale predstaviť robrazovanie datasetov podľa ich Typu, tj. HVD, publikačné minimum .... Si stým OK?

**Comment by lk8w** [comment]
No ak nevieme urobiť často sťahované dynamicky môžeme tam niektoré dať napevno podľa štatistiky čo mám od NASES:

Register adries - Ministerstvo vnútra SR
Vestník Úradu priemyselného vlastníctva SR - Úrad priemyselného vlastníctva Slovenskej republiky
Hlavný zoznam liekov s platnou registráciou na území SR a 6 ďalších prehľadných zoznamov (ATC, FIRMA, IS, ŠTÁTY, TYPY REGISTRÁCIÍ a VÝDAJE) - Štátny Ústav pre kontrolu liečiv
Počet prístupov na ÚPVS za deň - Národná agentúra pre sieťové a elektronické služby - NASES
Register adries - Zmenové dávky - Ministerstvo vnútra SR
Počet prístupov na ÚPVS - Národná agentúra pre sieťové a elektronické služby - NASES
Zoznam vyplatených faktúr PPA - Pôdohospodárska platobná agentúra
Programy schôdzí 8. volebného obdobia - Kancelária Národnej rady SR
Programy schôdzí 7. volebného obdobia - Kancelária Národnej rady SR
Zoznam rozhodnutí PMÚ SR - Protimonopolný úrad SR, Bratislava
Register poľovných revírov (PR) - Národné lesnícke centrum
Adresy podľa krajov - Ministerstvo vnútra SR
Zoznam faktúr PMÚ SR - Protimonopolný úrad SR, Bratislava
Zoznam OVM s pridelenou rolou na vytváranie listinného rovnopisu v schránke - Národná agentúra pre sieťové a elektronické služby - NASES
Zoznam objednávok PMÚ SR - Protimonopolný úrad SR, Bratislava

Čo sa týka API, tak by sme to vedeli rozlíšiť podľa formátu "api, json", lenže to nie je v tých metadátach :(
To HVD, PM, je OK len tiež otázne či k tomu sú metadáta.

**Comment by hornik-informo** [comment]
Táto požiadavka nebola zahrnutá v M2 a aj tak prišla po termíne. Môžeme ju riešiť v rámci M4, ak bude presne zadefinovaná.

**Comment by miroslavliska** [comment]
Tento task zatvaram, nepredpokladam ze nam zvysi cas toto riesit v najblizsom case, je potrebne sa zamerat na samotne metadata a s tym suvisiace vec. V buducnosti by to bolo dobre zintegrovat z nejakym CMS systemom, aby sa dal obsah menit editorskym sposobom.
