### ISSUE TITLE
 Nie je možné rozkliknúť položku Správa

### ISSUE THREAD

**Issue by lk8w** [slovak-egov/nkod-portal#80]
1. Prihlásenie pomocou OP
2. Kliknutie na SPARQL

Nie je možné rozkliknúť položku Správa
Na to aby ju bolo možné rozkliknúť treba opäť kliknúť na SPARQL

Firefox 122.0

**Comment by hornik-informo** [comment]
Na toto sa ešte pozrieme.

**Comment by hornik-informo** [comment]
Tento problém bol odstránený.

**Comment by lk8w** [comment]
môžeš zavrieť Miro, už to funguje
