### ISSUE TITLE
Vyhľadávanie v správe datasetov podľa textových vlastností

### ISSUE THREAD

**Issue by hornik-informo** [slovak-egov/nkod-portal#82]
Do správy datasetov by som odporúčal pridať aspoň vyhľadávanie v textoch. Neskôr by mohli pribudnúť aj ďalšie filtre.

**Comment by hornik-informo** [comment]
Tento task bol nasadený 20. februára, len sa zabudlo ho aktualizovať.

**Comment by miroslavliska** [comment]
OK, ďakujem za info. Otestoval som vyhľadávanie podľa slov v popise datasetu. Funguje, zatváram task.
