### ISSUE TITLE
Neumožňovať výber "môže obsahovať osobné údaje"

### ISSUE THREAD

**Issue by hornik-informo** [slovak-egov/nkod-portal#83]
Ak som tomu správne porozumel, tak v českom NKOD nie je možné pri pridávaní distribúcií zvoliť voľbu "môže obsahovať osobné údaje" - zadávateľ musí jasne zvoliť, či obsahuje alebo nie. Voľba "môže obsahovať" je len dočasná pre migráciu, kým sa neurčí inak.

Znamenalo by to, že nebude možné pridať distribúciu s voľbou "môže obsahovať osobné údaje" a aj pri aktualizácii distribúcie nebude možné uložiť distrubúciu s touto voľbou pre osobné údaje.

**Comment by miroslavliska** [comment]
> Ak som tomu správne porozumel, tak v českom NKOD nie je možné pri pridávaní distribúcií zvoliť voľbu "môže obsahovať osobné údaje" - zadávateľ musí jasne zvoliť, či obsahuje alebo nie. Voľba "môže obsahovať" je len dočasná pre migráciu, kým sa neurčí inak.
> 
> Znamenalo by to, že nebude možné pridať distribúciu s voľbou "môže obsahovať osobné údaje" a aj pri aktualizácii distribúcie nebude možné uložiť distrubúciu s touto voľbou pre osobné údaje.

Suhlasim s ceskym riesenim.

**Comment by hornik-informo** [comment]
Zmena bola nasadená.

**Comment by miroslavliska** [comment]
Prave som to testoval na prode, data.slovensko.sk a stale si mozem vybrat hodnotu - Moze obsahovat osobne udaje
![image](https://github.com/slovak-egov/nkod-portal/assets/37801000/4a18fa9e-57bc-4e11-a5db-4aca30c8d3e5)

**Comment by hornik-informo** [comment]
Priamo výber možný je pre zabezpečenie kompatibility s distribúciami, ktoré túto honotu majú z harvestra, ale nie je možné uložiť takúto distribúciu.

![image](https://github.com/slovak-egov/nkod-portal/assets/144911183/819b5c94-4bbf-4abd-975f-82efc90d8844)

**Comment by miroslavliska** [comment]
OK, rozumiem. Je to v poriadku, zatvaram task.
