### ISSUE TITLE
Určenie limitu pre veľkosť distribúcie

### ISSUE THREAD

**Issue by hornik-informo** [slovak-egov/nkod-portal#84]
Navrhujem jasne stanoviť limit pre maximálnu veľkosť distribúcie hostovanej priamo na data.slovensko.sk a túto hodnotu komunikovať používateľovi pri vkladaní súboru a pri väčšom súbore ho upozorniť na chybu.

Na úvod by som odporúčal stanoviť limit 30 MB.

**Comment by miroslavliska** [comment]
> Navrhujem jasne stanoviť limit pre maximálnu veľkosť distribúcie hostovanej priamo na data.slovensko.sk a túto hodnotu komunikovať používateľovi pri vkladaní súboru a pri väčšom súbore ho upozorniť na chybu.
> 
> Na úvod by som odporúčal stanoviť limit 30 MB.

Suhlasim. Tak sme sa dohodli na spolocnom stretnuti vsetci.

**Comment by miroslavliska** [comment]
Uz ste to prosim nastavili, aby som mohol uzavriet task?

**Comment by miroslavliska** [comment]
OK, nevsimol som si, ze sa mi zobrazuje hlaska - pri nahravani doslo k chybe. Takto je to za mna OK ,pretoze pri pridavani datasetu je intofmacia, ze max 30MB.
