### ISSUE TITLE
Pridanie podpory/služieb pre nových poskytovateľov identity pre členov OD2.0-Komunity pre Google a slovensko.sk

### ISSUE THREAD

**Issue by hornik-informo** [slovak-egov/nkod-portal#85]
Komponent IAM a webový portál sa upraví tak, aby bolo možné využiť aj iných poskytovateľov identity ako slovensko.sk pre fyzické osoby bez náväznosti na poskytovateľov otvorených dát. 
Všetky oprávnenia k publikovaniu dát budú aj naďalej viazané na identity zo slovensko.sk. Nových poskytovatyeľov budú využívať len fyzické osoby pre pripravované funkcionality komunity na data.slovensko.sk.

V rámci tohto tasku sa pridá podpora pre Google OAuth 2.0 a registrácia a prihlasovanie menom a heslom. Registrovaní používatelia s menom a heslom budú musieť overiť svoju e-mailovú adresu (pre nasadenie sa musí doriešiť odosielanie e-mailov z portálu).

Prosím o schálenie.

**Comment by miroslavliska** [comment]
Suhlasim. Takto sme sa dohodli na spolocnom internom meetingu.
