### ISSUE TITLE
Neumožňovať úpravy importovaných datasetov a distribúcií z lokálnych katalógov

### ISSUE THREAD

**Issue by hornik-informo** [slovak-egov/nkod-portal#88]
Importované datasety a distribúcie z LKODov sa zobrazujú v správe poskytovateľa dát, ale nebude ich možné upraviť ani odstrániť.

Prosím o schválenie.

**Comment by miroslavliska** [comment]
> Importované datasety a distribúcie z LKODov sa zobrazujú v správe poskytovateľa dát, ale nebude ich možné upraviť ani odstrániť.
> 
> Prosím o schválenie.
> 

Ano, potvrdzujem tuto funkcionalitu. 
Data z naharvestovanych katalogov sa musia menit v zdrojovom katalogu LKOD, nie v NKOD. 
NKOD si to bude denne harvetovat. 

ML

**Comment by hornik-informo** [comment]
Toto je zapracované, ale prejaví sa to až keď začne reálne portál načítavať harvestované datasety - až vtedy budú rozlíšené datasety, ktoré sú v NKOD a tie, ktoré patria do LKODov.
