### ISSUE TITLE
Pridanie stránkovania pre zoznam datasetov v rámci dátovej série

### ISSUE THREAD

**Issue by miroslavliska** [slovak-egov/nkod-portal#89]
Keďže tento zoznam má často 100vky poožiek, je potrebné spracovať stránkovanie. 
Napr: https://data.slovensko.sk/datasety/6a81933d-2871-46b9-a26e-8ca980f83e99

**Comment by hornik-informo** [comment]
Zmena bola nasadená.

**Comment by miroslavliska** [comment]
Potvrdzujem riešenie.
