### ISSUE TITLE
Pridanie odkazu na metodický portál opendata.gov.sk

### ISSUE THREAD

**Issue by lk8w** [slovak-egov/nkod-portal#9]
Umiestniť do portálu odkaz na metodický portál otvorených dát (https://wiki.vicepremier.gov.sk/display/opendata)
Umiestniť do portálu odkaz na školenia k otvoreným dátam.

**Comment by miroslavliska** [comment]
> Umiestniť do portálu odkaz na školenia k otvoreným dátam.


Ďaľšie odkazy by som tu už nedával, ako školenia, referencie, návody, ...., To už nech je na tom metodickom portáli správne pripravené.

**Comment by hornik-informo** [comment]
Táto požiadavka nebola zahrnutá v M2 a aj tak prišla po termíne. Môžeme ju riešiť v rámci M4, ak bude zadefinované kde a akým spôsobom má byť zapracovaný odkaz.
