### ISSUE TITLE
Pre hodnoty EÚ číselníkov pridanie URL dereferenciácie na znalosti.gov.sk

### ISSUE THREAD

**Issue by miroslavliska** [slovak-egov/nkod-portal#94]
V detaile distribúcie je potrebné zmeniť textovú hodnotu na URL link v nasledovných hodnotách

- [ ] Typ autorského diela
- [ ] Typ originálnej databázy
- [ ] Typ špeciálnej právnej ochrany databázy
- [ ] Formát súboru na stiahnutie
- [ ] Typ média súboru na stiahnutie

kde zobrazena textova hodnota ma byt zaroven URL odkaz smerujuci na: 
https://znalosti.gov.sk/resource?uri=[URI-hodnoty-ciselnika]
 
napr. hodnota z EU číselníka licencií: 
[Creative Commons Uvedenie Autora 4.0 Medzinárodný](https://znalosti.gov.sk/resource?uri=http://publications.europa.eu/resource/authority/licence/CC_BY_4_0)

**Comment by miroslavliska** [comment]
Toto zaraďujem na WPNKOD-SLA, implementácia je minimálna, len URL linka smerujúca na znalosti.gov.sk

**Comment by hornik-informo** [comment]
Zmena bola nasadená.

**Comment by miroslavliska** [comment]
Ano vidim, na našej strane zostáva naloadovať do znalosti EÚ číselník licencií. 
https://github.com/slovak-egov/centralny-model-udajov/issues/12
