### ISSUE TITLE
Uchovávanie dátumových hodnôt v datasetov v RDF serializácii v štandardnom formáte xsd:dateTime

### ISSUE THREAD

**Issue by miroslavliska** [slovak-egov/nkod-portal#95]
Prosim o zmenu datumovych hodnot v suborovej serializacii datasetov v adresari **/data/registration/public/dataset_registration/**

![image](https://github.com/slovak-egov/nkod-portal/assets/37801000/f7197cc1-478d-4c11-aa4b-c1d1a86cd87e)

na

```
 <http://purl.org/dc/terms/issued> "2020-05-13T11:36:28"^^<http://www.w3.org/2001/XMLSchema#dateTime>;
 <http://purl.org/dc/terms/modified> "2020-05-13T11:36:28"^^<http://www.w3.org/2001/XMLSchema#dateTime>;

```
tj. na štandardný formát xsd:dateTime.

**Comment by miroslavliska** [comment]
> Dátumy boli upravené, štandard pripúšta (a je to aj odporúčané), špecifikovať časové pásmo (Z - UTC).
> 
> Ak by to bolo problém, tak to odstránime.
> 
> "2024-02-29T14:22:27Z"^^xsd:dateTime

Ano, my sme aj pouzivali dost timezonu. Myslim ale ze SK je v UTC+1 zone, cize format by mal byt takyto

**"2024-02-29T14:22:27+01:00"^^xsd:dateTime**

pricom este presnejsi moze byt

"2024-02-29T14:22:27.0000+01:00"^^xsd:dateTime

**Comment by hornik-informo** [comment]
Ten čas je v UTC a z toho sa odfvodzuje čas v akejkoľvek zóne. Polovicu roka je SK UTC+1 a polovicu v UTC+2.

**Comment by miroslavliska** [comment]
> Ten čas je v UTC a z toho sa odfvodzuje čas v akejkoľvek zóne. Polovicu roka je SK UTC+1 a polovicu v UTC+2.

aha rozumiem, teda snazil som sa to pochopit. cize pre overenie, ak vznikne dataset slovenskeho casu 12:30, tak v UTC v subore je to 13:30Z. tak?

**Comment by hornik-informo** [comment]
Teraz (21:02) ked vznikde dataset tak bude zapísane:
dct:issued "2024-02-29T20:02:15Z"^^xsd:dateTime;
dct:modified "2024-02-29T20:02:15Z"^^xsd:dateTime;

My sme o hodinu vopred, čiže UTC čas je o hodinu menej.

**Comment by miroslavliska** [comment]
Nasadil som poslednu verziu, pozeram sa na log a vidim ze jedna property je stale este nenaformatovana 
![image](https://github.com/slovak-egov/nkod-portal/assets/37801000/c2a6bdc2-473e-4c7a-9e5f-dcfed636f8a2)

**Comment by hornik-informo** [comment]
Už by mali byť všetky v jednotnom formáte.

**Comment by miroslavliska** [comment]
Stále vidím veľmi veľa nesprávnych formátov - dátum modifikácie:
napr. v súbore: 00e60b20bbdf52c5ec0a76bc7d9f63a7.ttl
![image](https://github.com/slovak-egov/nkod-portal/assets/37801000/46aff36e-36ff-4e0a-a3fc-b1c885737f85)

**Comment by hornik-informo** [comment]
Ešte raz som to nechal zbehnúť a výsledok som prekontroloval skriptom. Nové súbory som poslal mailom.

**Comment by miroslavliska** [comment]
Vyzera to byt v poriadku, zatvaram task.
