### ISSUE TITLE
Nesprávne vlastnosti poskytovateľa údajov v serializácii

### ISSUE THREAD

**Issue by miroslavliska** [slovak-egov/nkod-portal#96]
V súčanosti je v rámci definície údajov v subore v adresari **/data/registration/public/publisher_registration/** o poskytovateľovi evidovaný 
- názov, merania kvality

avšak má tam byť
- názov, právna forma (bez merania kvality) . príklad pre ŠÚ je nasledovný:

```
@prefix foaf: <http://xmlns.com/foaf/0.1/> .
@prefix ls: <https://data.gov.sk/def/ontology/legal-subject/> .
@prefix subject: <https://data.gov.sk/id/legal-subject/> .
@prefix type: <https://data.gov.sk/def/legal-form-type/> .

subject:00166197 a foaf:Agent ;
    foaf:name "Štatistický úrad SR"@sk ;
    ls:legalFormType type:382 .
```

**Comment by hornik-informo** [comment]
Právnu formu sme nedostali, preto tam nemôže byť.
Meranie kvality môžeme odstrániť, ale tiež sme ho tak dostali z harvestra.

**Comment by hornik-informo** [comment]
Meranie kvality bolo odstránené.
