### ISSUE TITLE
Nesprávne URI poskytovateľov

### ISSUE THREAD

**Issue by miroslavliska** [slovak-egov/nkod-portal#97]
V súvislosti s dnešným problémom, kde sa pri ručnej zmene URI pri poskytovateľa Úrad pre dohľad nad zdravotnou starostlivosťou 
`https://data.gov.sk/id/legal-subject/fccf022a-284c-4927-b4f1-b4ec84adb495
`
zmenilo ručne na 
`https://data.gov.sk/id/legal-subject/30796482
`
načo sa stratili údaje (rozlišli sa identifikátory), som našiel viacero poskytovateľov, ktorí majú nesprávne URI, a neviem to už v harvestri opraviť. 

Týmto dotazom cez SPARLQ Endpoint 
```
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX dcat: <http://www.w3.org/ns/dcat#>
SELECT distinct ?publisher ?name
{
  ?dataset a dcat:Dataset .
  ?dataset dct:publisher ?publisher .
  ?publisher foaf:name ?name .
  
  FILTER (contains(strafter(str(?publisher), "https://data.gov.sk/id/legal-subject/"),"-"))
}
```

je získaný súbor s **12 poskytovateľmi** s URI, kde je namiesto iča použitý hash. Do toho CSVčka som pridal aj správne IČO, aby sa to ľahšie opravilo. Tieto nesprávne identifikátory sa musia vymeniť za správne všade, kde sa používajú.
[NekorektneURIposkytovatela.csv](https://github.com/slovak-egov/nkod-portal/files/14450806/NekorektneURIposkytovatela.csv)

Ešte dopĺňam že by sa asi malo zakázať meniť URI pre editácii. Len pri vytváraní nového poskytovateľa sa to môže natypovať.

**Comment by MarkySim** [comment]
Nemáme tam nejaký bug pri pridávaní nového datasetu?

**Comment by miroslavliska** [comment]
> Nemáme tam nejaký bug pri pridávaní nového datasetu? Podľa informácií tam predtým tento problém nebol.

Ja len pre zápis. Práve som vytvoril nového poskytovateľa NOCKu a vidím aj súbor, a tam je URI správne tak, ako som zadal.

```
<https://data.gov.sk/id/legal-subject/00164615> a foaf:Agent;
                                                foaf:homepage <https://www.nocka.sk/>;
                                                foaf:mbox "nocka@nocka.sk";
                                                foaf:name "Národné osvetové centrum"@sk;
                                                foaf:phone "";
                                                ls:legalForm <https://data.gov.sk/def/legal-form-type/331>.
```

**Comment by lk8w** [comment]
Keď pozerám na ten zoznam problémových OVM tak mi príde, ze či to nie sú tie čo v poslednom čase pridávali dataset/y.
![obrázok](https://github.com/slovak-egov/nkod-portal/assets/149062360/ac91ec9b-db36-478b-b29a-21dd35f623dc)

**Comment by hornik-informo** [comment]
Tieto URI poskytovateľov prišli z data.gov.sk. S datasetmi to nesúvisí.

**Comment by miroslavliska** [comment]
Teraz keĎ som študoval tie tri zdrojové adresáre, tak v súbore 2958309aaaa64060b53eee476ec638ff.ttl vidím
nesprávny názov - Levice (je to MIRRI).

![image](https://github.com/slovak-egov/nkod-portal/assets/37801000/a8c4e0ae-6eb3-4330-b33d-61936dc07135)

**Comment by miroslavliska** [comment]
> Keď pozerám na ten zoznam problémových OVM tak mi príde, ze či to nie sú tie čo v poslednom čase pridávali dataset/y.

No, niečo na tomto môže byť. P. @hornik-informo , zda sa mi ze s týmto suvisi aj tento problem https://github.com/slovak-egov/nkod-portal/issues/103

**Comment by hornik-informo** [comment]
Takto to prišlo z harvestra, toto je priamo výstup SPARQL zo dňa importu (subject - predicate - object):

![image](https://github.com/slovak-egov/nkod-portal/assets/144911183/4b8d4a58-6cd4-45c6-ad84-4f65264e094d)

Vzniklo to zrejeme tu:
https://github.com/datova-kancelaria/nkod-registrace/blob/main/poskytovatel%C3%A9/00307203.ttl

**Comment by miroslavliska** [comment]
Ano, pravda, ten isty pripad. Moja chyba, develop nebol mergnuty do produ. Prosim opravit v subore v NKODe.

**Comment by hornik-informo** [comment]
Pozmenili sme URI poskytovatľov podľa CSV.

**Comment by miroslavliska** [comment]
OKI, ďakujem za vyriešenie. Task zatváram.
